-- Create the Reports table
CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  type TEXT NOT NULL,
  severity_level TEXT NOT NULL,
  severity_score INTEGER NOT NULL,
  description TEXT NOT NULL,
  suggested_action TEXT,
  location JSONB, -- Storing { lat: number, lng: number, address: string }
  image_url TEXT,
  status TEXT DEFAULT 'Pending' NOT NULL,
  user_id UUID REFERENCES auth.users(id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public reports are viewable by everyone" 
  ON reports FOR SELECT 
  USING (true);

CREATE POLICY "Authenticated users can insert reports" 
  ON reports FOR INSERT 
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update their own reports" 
  ON reports FOR UPDATE 
  USING (auth.uid() = user_id);
